# Generated by Django 5.1.2 on 2024-10-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_ciudad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='notas_importantes',
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(default='Sin apellido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='documento',
            field=models.CharField(default='Sin apellido', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='Sin apellido', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
    ]
