# Generated by Django 5.1.2 on 2024-10-24 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_paciente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='gestion.paciente'),
            preserve_default=False,
        ),
    ]
