# Generated by Django 5.1.2 on 2024-10-24 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_tratamiento_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tratamiento',
            old_name='descripcion',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='nombre',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fecha',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.paciente'),
        ),
    ]
