# Generated by Django 5.1.2 on 2024-10-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_rename_descripcion_tratamiento_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
